language: node_js
node_js:
- 8.11.3
branches:
  only:
  - source

install: npm install

before_script:
- git config --global user.name "Shaw"
- git config --global user.email "lsk.boy.f@gmail.com"
- sed -i "s/__GITHUB_TOKEN__/${GITHUB_TOKEN}/" _config.yml

script: npm run build
